INSERT INTO categories (name, slug, description, sort_order, show_on_homepage) VALUES
  ('AI', 'ai', 'Artificial intelligence projects', 1, TRUE),
  ('IoT', 'iot', 'Internet of Things projects', 2, TRUE),
  ('Robotics', 'robotics', 'Robotics and automation projects', 3, TRUE),
  ('Physics', 'physics', 'Physics research and prototypes', 4, TRUE),
  ('Healthcare', 'healthcare', 'Health and medical innovation projects', 5, TRUE),
  ('Machine Learning', 'machine-learning', 'Machine learning projects', 6, TRUE),
  ('Deep Learning', 'deep-learning', 'Deep learning projects', 7, TRUE),
  ('Data Science', 'data-science', 'Data science projects', 8, TRUE),
  ('Chemistry', 'chemistry', 'Chemistry projects', 9, TRUE),
  ('Biology', 'biology', 'Biology projects', 10, TRUE),
  ('Cyber Security', 'cyber-security', 'Security and privacy projects', 11, TRUE),
  ('Blockchain', 'blockchain', 'Blockchain projects', 12, TRUE),
  ('Cloud Computing', 'cloud-computing', 'Cloud and distributed systems projects', 13, TRUE),
  ('Agriculture', 'agriculture', 'Agri-tech projects', 14, TRUE),
  ('Education', 'education', 'Education technology projects', 15, TRUE),
  ('Environment', 'environment', 'Environment and sustainability projects', 16, TRUE),
  ('Renewable Energy', 'renewable-energy', 'Renewable energy projects', 17, TRUE),
  ('Electronics', 'electronics', 'Electronics projects', 18, TRUE),
  ('Mechanical', 'mechanical', 'Mechanical engineering projects', 19, TRUE),
  ('Civil Engineering', 'civil-engineering', 'Civil engineering projects', 20, TRUE)
ON CONFLICT (slug) DO UPDATE SET show_on_homepage = TRUE;
